=== flotang-gtt/ThermML/schema/drafts/johan.zietsman-20240528/tdb.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema
        targetNamespace="http://calphad.org/thermoml/0.0"
        elementFormDefault="qualified"
        version="0.0"
        xmlns="http://calphad.org/thermoml/0.0"
        xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="database" type="DatabaseType"/>

    <xs:complexType name="NonChemicalPotentialType">
        <xs:attribute name="id"      type="xs:ID"      use="required"/>
        <xs:attribute name="symbol"  type="xs:string"  use="required"/>
        <xs:attribute name="units"   type="xs:string"   use="required"/>
    </xs:complexType>
    
    <xs:complexType name="SystemComponentType">
        <xs:attribute name="id"          type="xs:ID"      use="required"/>
        <xs:attribute name="symbol"      type="xs:string"  use="required"/>
        <xs:attribute name="molar_mass"  type="xs:float"   use="optional"  default="0.0"/>
        <xs:attribute name="refstate"    type="xs:string"  use="optional"  default="0.0"/>
        <xs:attribute name="h298"        type="xs:float"   use="optional"  default="0.0"/>
        <xs:attribute name="s298"        type="xs:float"   use="optional"  default="0.0"/>
    </xs:complexType>

    <xs:complexType name="StoichiometryRecordType">
        <xs:attribute name="sc_id"       type="xs:IDREF"   use="required"/>
        <xs:attribute name="coeff"       type="xs:float"   use="optional"  default="1.0"/>
    </xs:complexType>

    <xs:complexType name="SpeciesType">
        <xs:sequence>
            <xs:element name="description" type="xs:string" minOccurs="0"/>
            <xs:element name="stoichiometry" type="StoichiometryRecordType" />
        </xs:sequence>
        <xs:attribute name="id"          type="xs:ID"      use="required"/>
        <xs:attribute name="formula"     type="xs:string"  use="required"/>
    </xs:complexType>

    <xs:complexType name="ExpressionTermType" abstract="true"/>

    <xs:complexType name="TextTermType">
        <xs:complexContent>
            <xs:extension base="ExpressionTermType">
                <xs:attribute name="coeff"     type="xs:float"   use="optional"  default="1.0"/>
                <xs:attribute name="text"      type="xs:string"  use="required"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="PowerTermType">
        <xs:complexContent>
            <xs:extension base="ExpressionTermType">
                <xs:attribute name="coeff"     type="xs:float"   use="optional"  default="1.0"/>
                <xs:attribute name="var"       type="xs:string"  use="optional"  default="T"/>
                <xs:attribute name="exponent"  type="xs:string"  use="optional"  default="0.0"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="LogXTermType">
        <xs:complexContent>
            <xs:extension base="ExpressionTermType">
                <xs:attribute name="coeff"  type="xs:float"   use="optional"  default="1.0"/>
                <xs:attribute name="base"   type="xs:string"  use="optional"  default="2.718281828459045"/>
                <xs:attribute name="var"    type="xs:string"  use="optional"  default="T"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="XLogXTermType">
        <xs:complexContent>
            <xs:extension base="ExpressionTermType">
                <xs:attribute name="coeff"     type="xs:float"   use="optional"  default="1.0"/>
                <xs:attribute name="var"      type="xs:string"  use="optional"  default="T"/>
                <xs:attribute name="base"   type="xs:string"  use="optional"  default="2.718281828459045"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="ExpressionLimitsType">
        <xs:attribute name="variable"  type="xs:string"  use="required"/>
        <xs:attribute name="min"       type="xs:float"  use="optional"/>
        <xs:attribute name="max"       type="xs:float"  use="optional"/>
    </xs:complexType>

    <xs:complexType name="ExpressionType" abstract="true">
        <xs:sequence>
            <xs:element name="limits"  type="ExpressionLimitsType"  minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="ConstantExpressionType">
        <xs:complexContent>
            <xs:extension base="ExpressionType">
                <xs:attribute name="value" type="xs:float" use="required"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="TextExpressionType">
        <xs:complexContent>
            <xs:extension base="ExpressionType">
                <xs:attribute name="text"      type="xs:string"      use="required"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="MultitermExpressionType">
        <xs:complexContent>
            <xs:extension base="ExpressionType">
                <xs:sequence>
                    <xs:element name="term"         type="ExpressionTermType"  maxOccurs="unbounded"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="FunctionType">
        <xs:sequence>
            <xs:element name="description"  type="xs:string"       minOccurs="0" />
            <xs:element name="expression"   type="ExpressionType"  maxOccurs="unbounded" />
        </xs:sequence>
        <xs:attribute name="id"      type="xs:ID"      use="required"/>
        <xs:attribute name="symbol"  type="xs:string"  use="required"/>
        <xs:attribute name="units"   type="xs:string"  use="required"/>
    </xs:complexType>

    <xs:complexType name="PhaseType" abstract="true">
        <xs:sequence>
            <xs:element name="description"    type="xs:string" minOccurs="0" />
            <xs:element name="function"  type="FunctionType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="id"    type="xs:ID"      use="required"/>
        <xs:attribute name="name"  type="xs:string"  use="required"/>
        <xs:attribute name="state" type="xs:string"  use="required"/>
    </xs:complexType>

    <xs:complexType name="FreeEnergyContributionType" abstract="true">
    </xs:complexType>

    <xs:complexType name="CEFFreeEnergyContributionType">
        <xs:complexContent>
            <xs:extension base="FreeEnergyContributionType">
                <xs:sequence>
                    <xs:element name="function"  type="FunctionType" minOccurs="1" maxOccurs="unbounded"/>
                </xs:sequence>
                <xs:attribute name="constituents" type="xs:IDREFS" use="required"/>
                <xs:attribute name="order" type="xs:float" use="required"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="CEFSublatticeType">
        <xs:sequence>
            <xs:element name="gContribution" type="CEFFreeEnergyContributionType" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="multiplicity" type="xs:int" use="required"/>
        <xs:attribute name="constituents" type="xs:IDREFS" use="required"/>
    </xs:complexType>

    <xs:complexType name="CEFPhaseType">
        <xs:complexContent>
            <xs:extension base="PhaseType">
                <xs:sequence>
                    <xs:element name="sublattice" type="CEFSublatticeType" maxOccurs="unbounded" />
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="DatabaseType">
        <xs:sequence>

            <xs:element name="description" type="xs:string" minOccurs="0"/>

            <xs:element name="nonChemicalPotential">
                <xs:complexType>
                    <xs:sequence minOccurs="1" maxOccurs="unbounded">
                        <xs:element name="nonChemicalPotential" type="NonChemicalPotentialType" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>

            <xs:element name="systemComponents">
                <xs:complexType>
                    <xs:sequence minOccurs="1" maxOccurs="unbounded">
                        <xs:element name="systemComponent" type="SystemComponentType" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>

            <xs:element name="species">
                <xs:complexType>
                    <xs:sequence minOccurs="1" maxOccurs="unbounded">
                        <xs:element name="specie" type="SpeciesType" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>

            <xs:element name="functions">
                <xs:complexType>
                    <xs:sequence minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="function" type="FunctionType" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>

            <xs:element name="phases">
                <xs:complexType>
                    <xs:sequence minOccurs="1" maxOccurs="unbounded">
                        <xs:element name="phase" type="PhaseType" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>

        </xs:sequence>
        <xs:attribute name="name" type="xs:string" />
    </xs:complexType>

</xs:schema>

=== flotang-gtt/ThermML/schema/drafts/johan.zietsman-20240528/more.xml
<database
        xmlns="http://calphad.org/thermoml/0.0"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns:xi="http://www.w3.org/2001/XInclude"
        xsi:schemaLocation="http://calphad.org/thermoml/0.0 xsd/tdb.xsd"

        name="Example Database">

    <description>
        This is an example thermodynamic database.
    </description>

    <nonChemicalPotential>
        <nonChemicalPotential id="ptT" symbol="T" units="K"/>
        <nonChemicalPotential id="ptP" symbol="P" units="bar"/>
        <nonChemicalPotential id="ptB" symbol="B" units="T"/>
    </nonChemicalPotential>

    <systemComponents>
        <systemComponent id="scVa" symbol="Va" />
        <systemComponent id="scMo" symbol="Mo" refstate="BCC_A2" molar_mass="95.940" h298="4589.0" s298="28.560" />
        <systemComponent id="scRe" symbol="Re" refstate="HCP_A3" molar_mass="186.21" h298="5355.5" s298="36.526" />
    </systemComponents>

    <species>

        <specie id="spVa" formula="Va" >
            <stoichiometry sc_id="scVa"/>
        </specie>

        <specie id="spMo" formula="Mo" >
            <stoichiometry sc_id="scMo"/>
        </specie>

        <specie id="spRe" formula="Re" >
            <stoichiometry sc_id="scRe"/>
        </specie>

    </species>

    <functions>

        <function id="fnR" symbol="R" units="J/mol/K">
            <description>
                https://physics.nist.gov/cgi-bin/cuu/Value?r
            </description>
            <expression value="8.314462618" xsi:type="ConstantExpressionType" />
        </function>

        <function id="fnRTlnP" symbol="RTlnP" units="???">
            <expression text="R*T*ln(1.0E-05)*P" xsi:type="TextExpressionType" />
        </function>

        <function id="fneVtoJ" symbol="eVtoJ" units="J/eV">
            <expression text="96485.5547" xsi:type="TextExpressionType" />
        </function>

        <function id="fnG58CHIMO" symbol="G58CHIMO" units="???">
            <expression text="-619.36214*eVtoJ" xsi:type="TextExpressionType" />
        </function>

        <function id="fnCINQ8" symbol="CINQ8" units="???">
            <expression value="58" xsi:type="ConstantExpressionType" />
        </function>

        <function id="fnTRENTE" symbol="TRENTE" units="???">
            <expression value="30" xsi:type="ConstantExpressionType" />
        </function>

        <function id="fnUNS58" symbol="UNS58" units="???">
            <expression text="CINQ8**(-1)" xsi:type="TextExpressionType" />
        </function>

        <function id="fnGCHIMO" symbol="GCHIMO" units="???">
            <expression text="G58CHIMO*UNS58" xsi:type="TextExpressionType" />
        </function>

        <function id="fnGCHIRE" symbol="GCHIRE" units="???">
            <expression text="G58CHIRE*UNS58" xsi:type="TextExpressionType" />
        </function>

        <function id="fnGSIGMO" symbol="GSIGMO" units="???">
            <expression text="G30SIGMO*UNS30" xsi:type="TextExpressionType" />
        </function>

        <function id="fnGSIGRE" symbol="GSIGRE" units="???">
            <expression text="G30SIGRE*UNS30" xsi:type="TextExpressionType" />
        </function>

        <function id="fnGSERMO" symbol="GSERMO" units="???">
            <expression text="-10.949432*EVTOJ" xsi:type="TextExpressionType" />
        </function>

        <function id="fnGSERRE" symbol="GSERRE" units="???">
            <expression text="-12.4224915*EVTOJ" xsi:type="TextExpressionType" />
        </function>

        <function id="fnGHSERMO" symbol="GHSERMO" units="???">
            <expression xsi:type="MultitermExpressionType">
                <limits variable="T" max="2896" />
                <limits variable="P" max="2" />
                <term coeff="-7.746302E+03"                           xsi:type="PowerTermType" />
                <term coeff="+6.581200E+04" var="T"  exponent="-1.0"  xsi:type="PowerTermType" />
                <term coeff="+1.319197E+02" var="T"  exponent="+1.0"  xsi:type="PowerTermType" />
                <term coeff="-3.443396E-03" var="T"  exponent="+2.0"  xsi:type="PowerTermType" />
                <term coeff="+5.662830E-07" var="T"  exponent="+3.0"  xsi:type="PowerTermType" />
                <term coeff="-1.309270E-10" var="T"  exponent="+4.0"  xsi:type="PowerTermType" />
                <term coeff="-2.356414E+01" var="T"                   xsi:type="XLogXTermType" />
            </expression>
            <expression xsi:type="MultitermExpressionType">
                <limits variable="T" max="5000" />
                <term coeff="-3.0556410000E+04"                           xsi:type="PowerTermType" />
                <term coeff="-4.8493150000E+33" var="T"  exponent="-9.0"  xsi:type="PowerTermType" />
                <term coeff=" 2.8355974600E+02" var="T"  exponent="+1.0"  xsi:type="PowerTermType" />
                <term coeff="-4.2638290000E+01" var="T"                   xsi:type="XLogXTermType" />
            </expression>
        </function>
        
          <function id="fnGHSERRE" symbol="GHSERRE" units="???">
            <expression xsi:type="MultitermExpressionType">
                <limits variable="T" max="1200" />
                <term coeff="-7.69527900E+03"                           xsi:type="PowerTermType" />
                <term coeff="+3.29150000E+04" var="T"  exponent="-1.0"  xsi:type="PowerTermType" />
                <term coeff="+1.28421589E+02" var="T"  exponent="+1.0"  xsi:type="PowerTermType" />
                <term coeff="-2.53505000E+03" var="T"  exponent="+2.0"  xsi:type="PowerTermType" />
                <term coeff="+1.92818000E-07" var="T"  exponent="+3.0"  xsi:type="PowerTermType" />
                <term coeff="-1.30927000E-10" var="T"  exponent="+4.0"  xsi:type="PowerTermType" />
                <term coeff="-2.43480000E+01" var="T"                   xsi:type="XLogXTermType" />
            </expression>
            <expression xsi:type="MultitermExpressionType">
                <limits variable="T" max="2400" />
                <term coeff="-1.5775998000E+04"                           xsi:type="PowerTermType" />
                <term coeff="+1.3762700000E+06" var="T"  exponent="-1.0"  xsi:type="PowerTermType" />
                <term coeff="+1.9466742600E+02" var="T"  exponent="+1.0"  xsi:type="PowerTermType" />
                <term coeff="+2.2456500000E-03" var="T"  exponent="+2.0"  xsi:type="PowerTermType" />
                <term coeff="-2.8183500000E-07" var="T"  exponent="+3.0"  xsi:type="PowerTermType" />
                <term coeff="-3.3586000000E+01" var="T"                   xsi:type="XLogXTermType" />
            </expression>
            <expression xsi:type="MultitermExpressionType">
                <limits variable="T" max="3458" />
                <term coeff="-7.0882739000E+04"                           xsi:type="PowerTermType" />
                <term coeff="+1.8075200000E+07" var="T"  exponent="-1.0"  xsi:type="PowerTermType" />
                <term coeff="+4.6211074900E+02" var="T"  exponent="+1.0"  xsi:type="PowerTermType" />
                <term coeff="+1.1849450000E-02" var="T"  exponent="+2.0"  xsi:type="PowerTermType" />
                <term coeff="-7.8895500000E-07" var="T"  exponent="+3.0"  xsi:type="PowerTermType" />
                <term coeff="-6.7956000000E+01" var="T"                   xsi:type="XLogXTermType" />
            </expression>
        </function>
    </functions>

    <phases>
        <phase id="phLiq" name="Liquid" state="L" xsi:type="CEFPhaseType">
            <sublattice multiplicity="1" constituents="spMo spRe">

                <gContribution constituents="spMo" order="0">
                    <function id="fnGLiqMo" symbol="GLiqMo" units="J/mol">
                        <expression xsi:type="MultitermExpressionType">
                            <limits variable="T" max="2896"/>
                            <term coeff="+3.4085045000E+04"                xsi:type="PowerTermType" />
                            <term coeff="+1.1722478800E+02"  exponent="1"  xsi:type="PowerTermType" />
                            <term coeff="-3.4433960000E-03"  exponent="2"  xsi:type="PowerTermType" />
                            <term coeff="+5.6628300000E-07"  exponent="3"  xsi:type="PowerTermType" />
                            <term coeff="-1.3092700000E-10"  exponent="4"  xsi:type="PowerTermType" />
                            <term coeff="+4.2451900000E-22"  exponent="7"  xsi:type="PowerTermType" />
                            <term coeff="+6.5812000000E+04"  exponent="-1" xsi:type="PowerTermType" />
                            <term coeff="-2.3564140000E+01"                xsi:type="XLogXTermType" />
                        </expression>
                        <expression xsi:type="MultitermExpressionType">
                            <limits variable="T" max="5000"/>
                            <term coeff="+3.5389630000E+03"              xsi:type="PowerTermType" />
                            <term coeff="+2.7166970000E+02" exponent="1" xsi:type="PowerTermType" />
                            <term coeff="-4.2638290000E+01"              xsi:type="XLogXTermType" />
                        </expression>
                    </function>
                </gContribution>

                <gContribution constituents="spRe" order="0">
                    <function id="fnGLiqRe" symbol="GLiqRe" units="J/mol">
                        <expression xsi:type="MultitermExpressionType">
                            <limits variable="T" max="1200" />
                            <term coeff="+1.6125604000E+04"              xsi:type="PowerTermType" />
                            <term coeff="+1.2207620900E+02" exponent="1" xsi:type="PowerTermType" />
                            <term coeff="-2.4348000000E+01"              xsi:type="XLogXTermType" />
                            <term coeff="-2.5350500000E-03" exponent="2" xsi:type="PowerTermType" />
